# Generated by Django 3.1.8 on 2021-05-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='%m/%d/%Y')),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
